apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: content-management
  name: content-management
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    app: content-management
status:
  loadBalancer: {}
