apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    app: content-management
  name: content-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-management
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5001"
      creationTimestamp: null
      labels:
        io.kompose.network/psd2-t12-default: "true"
        app: content-management
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
          image: mrizqullah/content-management:latest
          name: content-management
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {}
          # volumeMounts:
          #   - mountPath: /app
          #     name: content-management-claim0
      restartPolicy: Always
      # volumes:
      #   - name: content-management-claim0
      #     persistentVolumeClaim:
      #       claimName: content-management-claim0
status: {}
