apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: image-processing
    app: image-processing
  name: image-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-processing
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5003"
      creationTimestamp: null
      labels:
        io.kompose.network/psd2-t12-default: "true"
        io.kompose.service: image-processing
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
          image: mrizqullah/image-processing:latest
          name: image-processing
          ports:
            - containerPort: 5003
              hostPort: 5003
              protocol: TCP
          resources: {}
          # volumeMounts:
          #   - mountPath: /app
          #     name: image-processing-claim0
      restartPolicy: Always
      # volumes:
      #   - name: image-processing-claim0
      #     persistentVolumeClaim:
      #       claimName: image-processing-claim0
status: {}
