apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: recycling-center
  name: recycling-center
spec:
  type: LoadBalancer
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    app: recycling-center
status:
  loadBalancer: {}
